apiVersion: v2
name: librechat
description: Frontend for AI endpoints
type: application
version: 1.4.5
appVersion: v1.0.0
dependencies:
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.10.1
    condition: meilisearch.enabled
  - name: redis
    version: 20.2.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: mongodb
    version: 16.1.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled