apiVersion: v2
name: librechat
description: Frontend for AI endpoints
type: application
version: 1.4.3
appVersion: v0.7.3
dependencies:
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.10.1
    condition: meilisearch.enabled
  - name: redis
    version: 19.6.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: mongodb
    version: 15.6.24
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled