name: Lint Helm
# https://github.com/helm/chart-testing-action

on:
  push:
    branches:
      - main
    paths:
      - charts/**.yaml
      - charts/**.yml
  pull_request:
    paths:
      - charts/**.yaml
      - charts/**.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint_helm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.8.0

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs=charts/librechat --target-branch ${{ github.event.repository.default_branch }}

      #- name: Create kind cluster
      #  uses: helm/kind-action@v1.10.0

      #- name: Run chart-testing (install)
      #  run: ct install --target-branch ${{ github.event.repository.default_branch }}